<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.salary</groupId>
        <artifactId>hr-calculator-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>hr-web</artifactId>
    <name>HR Web Module</name>

    <dependencies>
        <!-- Внутренние модули -->
        <!-- Подключаем логику расчетов -->
        <dependency>
            <groupId>com.salary</groupId>
            <artifactId>hr-service</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Подключаем базу данных -->
        <dependency>
            <groupId>com.salary</groupId>
            <artifactId>hr-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Подключаем общие DTO -->
        <dependency>
            <groupId>com.salary</groupId>
            <artifactId>hr-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.salary</groupId>
            <artifactId>hr-batch</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Веб-стартер Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Драйвер PostgreSQL -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.salary.hrcalculatorapp.HrCalculatorApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>