spring:
  application:
    name: hr-calculator

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db # Имя вашей локальной БД
    username: postgres                          # Ваш логин в pgAdmin
    password: root                              # Ваш пароль в pgAdmin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update                          # Hibernate сам создаст таблицы при старте
    show-sql: true                              # Показывает SQL-запросы в консоли IDEA
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080                                    # Порт, который вы вызываете в .http файле
